### ISSUE TITLE
Crash on android unity 4.6.3

### ISSUE THREAD

**Issue by jessicard** [bugsnag/bugsnag-unity#11]
"I'm on Unity 4.6.3. From the stack trace it looks more like its trying to log a debug via a method but it seems not available with expected signature.

This crash I got from Logcat when testing on android device. Bugsnag crashes the app after this issue. Nothing is logged on Bugsnag as you can see Bugsnag crashed.

I'm tracking all debug logs as well when I tried this. This happens random."

```
03-15 12:05:43.696	com.company.product 10856	10886	F	art art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: the return type of CallStaticObjectMethodA does not match void com.bugsnag.android.Bugsnag.notify(java.lang.String, java.lang.String, java.lang.StackTraceElement[], com.bugsnag.android.Severity, com.bugsnag.android.MetaData)
```

**Comment by qiankanglai** [comment]
Please merge it!
I had this problem too for unity 5.1.4f1, and Bugsnag is leading crash when collecting error
