### ISSUE TITLE
Duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by natalieSED** [bugsnag/bugsnag-unity#114]
### Description
Updating Bugsnag to 4.0 in our Unity project

### Issue
Bugsnag library conflicts with other libraries when trying to build xcodeproj to iPhone

### Environment

* bugsnag-unity version: 4.0
* Unity version: 2017.2.0p1
* Operating system name and version: macOS High Sierra 10.13.6
* Target platform names and versions: iPhone 7, 12.1
* Initializing bugsnag via the Unity UI or in code? code 

### Xcode Error
```
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from ...Libraries/libiPhone-lib.a(unwind_test_arm64.o)
duplicate symbol _OBJC_CLASS_$_AFImageCache in:
    ...Libraries/Plugins/iOS/libiOS_AFNetworkingUnity.a(UIImageView+AFNetworking.o)
duplicate symbol _OBJC_METACLASS_$_AFImageCache in:
   ...Libraries/Plugins/iOS/libiOS_AFNetworkingUnity.a(UIImageView+AFNetworking.o)
ld: 3 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kattrali** [comment]
Thanks for reporting, @natalieSED. Based on the error message, it looks like the duplicate symbols come from `libiOS_AFNetworkingUnity.a`, which is not added by bugsnag-unity. Maybe the problem is in a different dependency?

**Comment by natalieSED** [comment]
Is there something in Bugsnag 4.0 that could be conflicting there? It was
the only thing that I changed on this branch and we haven't had this issue
previously.

**Comment by kattrali** [comment]
I don't think so; I tried it on the same version of unity + macOS + iPhone running 12.1.1 without issue. What version of bugsnag did you upgrade from?

**Comment by kattrali** [comment]
Maybe a clean & rebuild in Xcode will fix it. Seems like the kind of thing that could happen with old artifacts around.
