### ISSUE TITLE
update documentation for Breadcrumbs.Leave so it tells you how to leave a longer message

### ISSUE THREAD

**Issue by tayl0r** [bugsnag/bugsnag-unity#130]
In the breadcrumb docs it does not tell you how to leave a longer message. It really should:

```
Breadcrumbs.Leave(logType.ToString(), BreadcrumbType.Log, new Dictionary<string, string> {
  { "message", longMessage },
});
```

Had to dig into the source code to figure that out since it's not really obvious that the dictionary would take a "message" key with the full text.

**Comment by kattrali** [comment]
Thanks for the report, @tayl0r. The docs weren't really clear here so I've made an update which will be live shortly.
