### ISSUE TITLE
[Android] user id not filled in for native crashes if you set user id after bugsnag.init

### ISSUE THREAD

**Issue by tayl0r** [bugsnag/bugsnag-unity#134]
### Description
I am setting the user id and I want to see that same user id on bugsnag issues for native crashes.
I think the problem is because I am calling Bugsnag.Init before I set the user id, so it sends the previous native crash before the user id is set. But that is going to be a typical workflow and there should be a mechanism to handle it.

### Issue
When I look at the bugsnag issue, the user id is the bugsnag generated user id and not my custom user id.

### Environment
Android

* bugsnag-unity version: 4.2.0
* Unity version: 2017.4.14f1
* Operating system name and version: building with OSX
* Target platform names and versions: Android 8.0 on HUAWEI ANE-LX2 (P20 Lite)
* Initializing bugsnag via the Unity UI or in code? UI

### Example code snippet

```
// after your app starts up, run this code somewhere to set the user id
// this will run after bugsnag initializes, because we want to capture errors and exceptions from the first moment possible, but we dont know their user id until later
		BugsnagUnity.Bugsnag.SetUser(guid, email, name);
		BugsnagUnity.Bugsnag.BeforeNotify(report => {
			report.Metadata.Add("user", new Dictionary<string, object> {{ "admin", isAdmin }, { "guid", guid }});
		});

// run this method and it will crash your android device. start it up again and you should get a SIGSEGV error in Bugsnag.
// Then look at your report in bugsnag, the user id will not be set properly.
public void MemoryCrash() {
	StartCoroutine(MemoryCrashCor());
}

IEnumerator MemoryCrashCor() {
	Debug.Log("MemoryCrashCor");
	System.Text.StringBuilder sb = new System.Text.StringBuilder();
	List<string> list = new List<string>();
	for (int i = 0; i < int.MaxValue; ++i) {
		if (i % 100 == 0) {
			yield return 1;
		}
		try {
			sb.AppendFormat("!! {0},{1},{2},{3} !!\n", i, i * 2, Mathf.Pow((float)i, 2f), int.MaxValue - i);
			list.Add(sb.ToString());
		} catch {
			Debug.Log("MemoryCrashCor .... BOOOM!!");
		}
	}
}
```

*Note:* In the Android docs it says there is a setting called `persistUserBetweenSessions ` (https://docs.bugsnag.com/platforms/android-kotlin/configuration-options/#setpersistuserbetweensessions) but that doesn't seem to exist for Unity. Mabye this would solve the problem?

**Comment by kattrali** [comment]
Thanks for the report, @tayl0r. This seems like a bug as calling `SetUser` should include the same ID in native reports.
