### ISSUE TITLE
xCode Compiler errors when using IL2CPP and Universal Architecture for unity ios build

### ISSUE THREAD

**Issue by sambauwens** [bugsnag/bugsnag-unity#14]
Using Unity 4.6.5 and xCode 6.3.1. I get compiler errors when building the xCode project generated by Unity with IL2CPP scripting backend and Universal architecture.

I get errors for the KSCrashReport.c file:

- Libraries/KSCrashReport.c:55:13: *Unknown type name 'ucontext64_t'; did you mean 'ucontext_t'?*

- Libraries/KSCrashReport.c:424:69: *No member named 'uc_mcontext64' in 'struct __darwin_ucontext'; did you mean 'uc_mcontext'?*

**Comment by ConradIrwin** [comment]
Hi @sambauwens,

This should be fixed with release 2.2.6, which includes the fix from KSCrash.

Conrad
