### ISSUE TITLE
Error on Android 2.3.6 

### ISSUE THREAD

**Issue by oddgames-david** [bugsnag/bugsnag-unity#16]
This reports whenever I log an exception. Lots of frames have passed before this is called and Bugsnag object is in the scene, enabled etc.

I don't get this error on other devices with a newer android os.

AndroidJavaException: java.lang.IllegalStateException: You must call Bugsnag.init before any other Bugsnag methods 
at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0  
UnityEngine.AndroidJNISafe.CallStaticVoidMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0  
UnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0  
UnityEngine.AndroidJavaObject.CallStatic (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0  
Bugsnag+NativeBugsnag.SetContext (System.String context) [0x00000] in /Assets/Standard Assets/Bugsnag.cs:138  
Bugsnag.set_Context (System.String value) [0x0000d] in /Assets/Standard Assets/Bugsnag.cs:218

**Comment by fractalwrench** [comment]
Closing as we now support API 14+
