### ISSUE TITLE
Update documentation for class/message split

### ISSUE THREAD

**Issue by golergka** [bugsnag/bugsnag-unity#17]
After going through Bugsnag documentation I noticed the split between Class and Message on error, and then found the split implemented with a regex in HandleLog method of Bugsnag.cs. It's nice that this is implemented, but it would be nicer if it was documented.

**Comment by kattrali** [comment]
Thank you for reporting this, @golergka. I'll take a look.

**Comment by CodeHex** [comment]
Thanks again for the feedback! We've updated the docs to describe this (https://docs.bugsnag.com/platforms/unity/configuration-options/#notifylevel)
