### ISSUE TITLE
[Windows] Cannot compose metadata in the same category.

### ISSUE THREAD

**Issue by technicalDeath** [bugsnag/bugsnag-unity#170]
### Description
I have separate parts of my application that want to add keys to the same Metadata categories.

Executing the following statements should be valid:
BugsnagUnity.Bugsnag.Metadata.Add( "myCategory", new Dictionary<string, string> { { "keyA", "valueA" } } ) ;
BugsnagUnity.Bugsnag.Metadata.Add( "myCategory", new Dictionary<string, string> { { "keyB", "valueB" } } ) ;

### Issue
Exception is thrown:
System.ArgumentException: An item with the same key has already been added. Key: myCategory

The Unity C# wrapper around the NativeClient uses a dictionary and naively calls .Add which will fail and throw exceptions if you attempt to add additional keys to the same category.

### Environment

* bugsnag-unity version: 4.6.4
* Unity version: 2018.4.3f1
* Operating system name and version: Windows 10
* Target platform names and versions: Android/iOS
* Initializing bugsnag via the Unity UI or in code? UI

### Example code snippet
BugsnagUnity.Bugsnag.Metadata.Add( "myCategory", new Dictionary<string, string> { { "keyA", "valueA" } } ) ;
BugsnagUnity.Bugsnag.Metadata.Add( "myCategory", new Dictionary<string, string> { { "keyB", "valueB" } } ) ;

Expectation: KeyA,ValueA and KeyB,ValueB are merged into the category.
Result: Exception is thrown.

```cs

```

**Comment by abigail-bugsnag** [comment]
Hi @technicalDeath thanks for the report! This indeed looks like a bug. 
We will look to get this fixed in a future release and will let you know when it has.

**Comment by technicalDeath** [comment]
Note: I was running in Unity editor on windows, but this issue is present on any Unity build platform (Android, iOS, etc.).

**Comment by technicalDeath** [comment]
@abigail-bugsnag Hi Abigail, I have implemented a fix for this issue which can be found here:
https://github.com/bugsnag/bugsnag-unity/compare/master...technicalDeath:allow_metadata_additions

Perhaps your team would like to integrate it. It has been thoroughly tested on my end on Windows, iOS, and Android.

Cheers!

**Comment by mattdyoung** [comment]
@technicalDeath 
Thanks! The team will take a look.
