### ISSUE TITLE
bugsnag-osx.bundle is not signed

### ISSUE THREAD

**Issue by freerangegreg** [bugsnag/bugsnag-unity#171]
We're getting an error when trying to use the library in a signed OSX build. Would it be possible for you to release a signed version of the native plugin?

```
Plugins: Couldn't open /Users/x/Desktop/1215842/Y.app/Contents/Plugins/bugsnag-osx.bundle/Contents/MacOS/bugsnag-osx, error: dlopen(/Users/x/Desktop/1215842/Y.app/Contents/Plugins/bugsnag-osx.bundle/Contents/MacOS/bugsnag-osx, 2): no suitable image found.  Did find:
	/Users/x/Desktop/1215842/Y.app/Contents/Plugins/bugsnag-osx.bundle/Contents/MacOS/bugsnag-osx: code signature in (/Users/x/Desktop/1215842/Y.app/Contents/Plugins/bugsnag-osx.bundle/Contents/MacOS/bugsnag-osx) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
```

**Comment by kattrali** [comment]
Yeah - thanks for the heads up. The builds should be signed by default, I'll need to check if something has gone awry in the release system. Was this on the latest version of the plugin or 4.6.1 like the newer issue?

**Comment by freerangegreg** [comment]
Sorry, didn't see the template when reporting this bug yesterday. This is 4.6.1, and it's an il2cpp OSX build.

**Comment by kattrali** [comment]
Thanks, that helps.

**Comment by freerangegreg** [comment]
Looks like this one was on our side. Our signing failed because we had extra folders in the plugin. (Perforce makes it nearly impossible to delete folders in Unity.)
