### ISSUE TITLE
 AndroidJavaException on Android with Unity 2019.2.6

### ISSUE THREAD

**Issue by khonkaengame** [bugsnag/bugsnag-unity#174]
I get AndroidJavaException error on android with Unity 2019.2.6

I use Bugsnag.unitypackage

It show this error when i change to another scene

09-22 22:13:55.948  9128  9155 E Unity   : AndroidJavaException: java.lang.UnsatisfiedLinkError: com.bugsnag.android.ndk.NativeBridge
09-22 22:13:55.948  9128  9155 E Unity   : java.lang.UnsatisfiedLinkError: com.bugsnag.android.ndk.NativeBridge
09-22 22:13:55.948  9128  9155 E Unity   :      at com.bugsnag.android.NativeInterface.configureClientObservers(NativeInterface.java:199)
09-22 22:13:55.948  9128  9155 E Unity   :      at com.bugsnag.android.Client.<init>(Client.java:247)
09-22 22:13:55.948  9128  9155 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
09-22 22:13:55.948  9128  9155 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source)
09-22 22:13:55.948  9128  9155 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
09-22 22:13:55.948  9128  9155 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:98)
09-22 22:13:55.948  9128  9155 E Unity   :      at android.os.Looper.loop(Looper.java:150)
09-22 22:13:55.948  9128  9155 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
09-22 22:13:55.948  9128  9155 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0
09-22 22:13:55.948  9128  9155 E Unity   :   at UnityEngine.AndroidJNISafe.NewObject (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0
09-22 22:13:55.948  9128  9155 E Unity   :   at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x000
09-22 22:14:13.905  9128  9155 E Unity   : AndroidJavaException: java.lang.UnsatisfiedLinkError: com.bugsnag.android.ndk.NativeBridge

**Comment by kattrali** [comment]
Thanks for the report, @khonkaengame. Can you share the following about how you are initializing Bugsnag and your environment:


* bugsnag-unity version?
* Is this an emulator?
* Android version?
* How are you initializing Bugsnag? Is it in a GameObject or in code (using `Bugsnag.Init()`)? Is Bugsnag initialized more than once?

**Comment by khonkaengame** [comment]
Q : bugsnag-unity version? :
A : v4.6.5

Q : Is this an emulator? :
A : It's not emulator, It's on huawei y6II

Q: Android version?
A: 6.0

Q:How are you initializing Bugsnag? Is it in a GameObject or in code
(using Bugsnag.Init())? Is Bugsnag initialized more than once?
Thank you for this question. I found it because of i initialized more than
once.

Thank you.

**Comment by kattrali** [comment]
Ah, good to hear that its resolved!
