### ISSUE TITLE
TimingTracker does not persist for life of application

### ISSUE THREAD

**Issue by technicalDeath** [bugsnag/bugsnag-unity#175]
### Description
The foreground status and duration values are not accurate if a new scene is loaded. The TimingTrackerBehaviour gets destroyed in this case and stops tracking foreground status.

Without the following tag specified on a Unity object, it will unload on scene change:
https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html

### Issue
Unity game loads.
Bugsnag initializes, which spawns the TimingTrackerBehaviour.
Game loads a new scene.
TimingTrackerBehaviour is destroyed.
inForground and durationInForeground values are not accurate in reports

### Environment

* bugsnag-unity version: 4.6.4
* Unity version: 2018.4.3f1
* Operating system name and version: Android or iOS, any version
* Target platform names and versions: Android, iOS
* Initializing bugsnag via the Unity UI or in code? UI

### Example code snippet
n/a

**Comment by mattdyoung** [comment]
Hi @technicalDeath 

Thanks for the report. We're taking a look.

**Comment by technicalDeath** [comment]
@mattdyoung @abigail-bugsnag I've made a fix for this issue:
https://github.com/bugsnag/bugsnag-unity/compare/master...technicalDeath:dont_destroy_timingtracker2

It has been tested across Windows, iOS, and Android, if you would like to integrate.

**Comment by mattdyoung** [comment]
@technicalDeath 
Thanks for sharing the fix!

It may be a little while until the team have bandwidth to review and formally test this, but we'll get to it when we can.

**Comment by yousif-bugsnag** [comment]
This is now fixed in [v5.0.0](https://github.com/bugsnag/bugsnag-unity/releases/tag/v5.0.0) 🎉
