### ISSUE TITLE
Specify available severity levels

### ISSUE THREAD

**Issue by golergka** [bugsnag/bugsnag-unity#18]
Currently, in this notification plugin, severity is described as a string, which lead me to believe (erroneously) that Bugsnag supports any string as "severity" setting for an issue. However, the notifier API says that severity only has three valid values: "error", "warning" and "info". The best way to reflect it in C# is using an enum instead of string, and [dotNET notifier plugin already has one](https://github.com/bugsnag/bugsnag-dotnet/blob/6d59e4b80eeb3f3c4f3811aef26a14ca36761b05/src/Bugsnag/Enums.cs#L11).

Refactoring Unity notifier plugin to use enum instead of string internally would prevent such confusion.

**Comment by kattrali** [comment]
That makes perfect sense. Thanks for the report, @golergka.
