### ISSUE TITLE
RegisterLogCallback is obsolete in Unity 5

### ISSUE THREAD

**Issue by golergka** [bugsnag/bugsnag-unity#19]
RegisterLogCallback, used in bugsnag SDK, is obsolete. Unity asks to use logMessageReceived event instead:

`UnityEngine.Application.RegisterLogCallback(UnityEngine.Application.LogCallback)' is obsolete:Application.RegisterLogCallback is deprecated. Use Application.logMessageReceived instead.'`

**Comment by kattrali** [comment]
Thank you for the report, @golergka. Working on a patch now.
