### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by BallerIndustries** [bugsnag/bugsnag-unity#2]
Testing out bugsnag for Unity right now. I'm getting an error on launch though:

DllNotFoundException: bugsnag
Bugsnag.Awake () (at Assets/Standard Assets/Bugsnag.cs:113)

Any ideas?

**Comment by snmaynard** [comment]
We don't currently support the editor so this isn't something we will fix in the short term. However we are in the process of releasing a new version of the library and that will play nicely (do nothing) in the editor.

Thanks!
