### ISSUE TITLE
Support for Google external dependency manager

### ISSUE THREAD

**Issue by jannekaisgg** [bugsnag/bugsnag-unity#201]
I've been testing out Bugsnag and run into a problem when targeting Android. The problem was caused by duplicate Kotlin libraries embedded into project. One version was part of the Bugsnag unity package and the second one were added through Google Dependency resolver as a dependency of MoPub.

I managed to fix the issue by removing the kotlin* libraries that were distributed as part of the unity package. 

It would be nice if Bugsnag would also support Google dependency manager and not embed the external libraries directly. This has become almost a standard and for example Firebase, Facebook and MoPub use it, as well as many other 3rd party plugins.

https://github.com/googlesamples/unity-jar-resolver

**Comment by phillipsam** [comment]
Hi @jannekaisgg - thanks for the feedback, we will take a look!

**Comment by benoitdion** [comment]
We're also seeing this. Confirming manually removing the kotlin libraries fixed the issue.

**Comment by Anaskahloon** [comment]
I was having same issue when I remove kotlin libraries build succeeded :D

**Comment by xander-jones** [comment]
Support for [EDM4U](https://github.com/googlesamples/unity-jar-resolver) has been added in `bugsnag-unity` https://github.com/bugsnag/bugsnag-unity/releases/tag/v6.3.0 🎉 . See the new menu item at Window/Bugsnag/Enable EDM Support.
