### ISSUE TITLE
[iOS] out of memory events do not include the real user id

### ISSUE THREAD

**Issue by troy-lamerton** [bugsnag/bugsnag-unity#216]
### Describe the bug

iOS out of memory events do not include the real user ID.
Instead, the user id appears to be a guid for the device.

The out of memory events are also missing configuration set immediately after `Bugsnag.Init()`, the user id is the most important thing for us though.

### Steps to reproduce

1. On iOS, init Bugsnag and set the user id to "bob1"
2. Trigger an out of memory crash
2. Reopen the app and initialize bugsnag again (so that OOM event is reported)
3. See that the event on bugsnag.com has some guid as the user id (should be "bob1")

### Environment
* Bugsnag version: v4.8.4
* Unity version: 2019.4.16f1
* iOS/Android/macOS/Windows/browser version: iOS 14.4
* simulator/emulator or physical device: physical iPhone 8
* Initializing bugsnag via a Unity GameObject or in code?: code
* Player Settings:
    * Scripting backend (Mono or IL2CPP): IL2CPP
    * API compatibility level for .NET: .NET 4.x
    * Stack Trace level for all error types (None/ScriptOnly/Full): ScriptOnly

### Example code snippet
```cs
    // init Bugsnag and trigger an out of memory crash
    public void TriggerOOM() {
		Bugsnag.Init("apikey", true);
        Bugsnag.Client.User.Id = "bob1";

        var list = new List<byte[]>();
        const int twentyMB = 20 * 1024 * 1024;
        while (true) {
            list.Add(new byte[twentyMB]);
        }
    }
```

This may be related to the already resolved issue [[Android] user id not filled in for native crashes if you set user id after bugsnag.init #134](https://github.com/bugsnag/bugsnag-unity/issues/134)

**Comment by xander-jones** [comment]
Hi @troy-lamerton, just ran a quick test with this (using https://github.com/bugsnag/bugsnag-unity/releases/tag/v4.8.5, note there are no iOS changes between this and v4.8.4, so would expect the exact same behaviour) and am seeing user information on OOM events on iOS:

![image](https://user-images.githubusercontent.com/9535852/110776411-f0e16100-8257-11eb-842c-58daed2c3efb.png)

The difference is how I'm setting the user data though. Can you please give this a go and let us know how you get on? https://docs.bugsnag.com/platforms/unity/#identifying-users

```c#
public class Bugsnag_Xander : MonoBehaviour
{
    void Start()
    {
        Bugsnag.Init("API_KEY", true);
        Bugsnag.SetUser("Xander", "xander@example.com", "Xander Name");
    }
// ...
```

**Comment by mattdyoung** [comment]
Closing this as we believe using `SetUser` should work. Do let us know if that doesn't resolve the issue.

**Comment by troy-lamerton** [comment]
I've been using `SetUser` for some weeks now.

- Initially it worked great, OOM reports had all the correct user info.
- Then OOM reports with wrong user id started appearing again, I'm not sure exactly when (some days ago).

For example: https://app.bugsnag.com/the-naughty-cult-ltd/clash-of-streamers-1/errors/5f9aef5809d334001779cc75?filters%5Bevent.since%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.since%5D%5B%5D%5Bvalue%5D=7d&filters%5Bdevice.model%5D%5B%5D%5Btype%5D=eq&filters%5Bdevice.model%5D%5B%5D%5Bvalue%5D=iPad11%2C6&filters%5Brelease.seen_in%5D%5B%5D%5Btype%5D=eq&filters%5Brelease.seen_in%5D%5B%5D%5Bvalue%5D=22.*&event_id=60bd1d1e007d00973d6f0000

Possible workaround:

- don't call `SetUser`
- set `User.Name = "my-custom-user-id"` 
- on dashboard, filter by `User.Id` or `User.Name`

**Comment by yousif-bugsnag** [comment]
Hi @troy-lamerton, so that we can investigate further would you be able to write to us at support@bugsnag.com with links to example events that do have the correct user info, as well as those that do not, as well as confirmation of exactly how you're setting the user info?

**Comment by troy-lamerton** [comment]
@yousif-bugsnag
Now that version 5 is released, I want to give version 5 a try before exploring this further (maybe it is fixed for us). Let's keep the issue closed for now.
