### ISSUE TITLE
Can not build the game with unity 2020.3.0f1

### ISSUE THREAD

**Issue by antpaw** [bugsnag/bugsnag-unity#221]
### Describe the bug
Can not build the game with unity 2020.3.0f1

### Steps to reproduce
1. Go to 'Build Settings'
2. Click on 'Build and Run'
3. See error "Missing .plist"

### Environment
* Bugsnag version: v4.8.6
* Unity version: 2020.3.0f1
* /macOS/:
* physical device: mac book pro
* Initializing bugsnag via a Unity GameObject or in code?: code
* Player Settings:
    * Scripting backend (Mono or IL2CPP): Mono
    * API compatibility level for .NET: .NET Standard 2.0
    * Stack Trace level for all error types (None/ScriptOnly/Full): ?

<details><summary>Error messages:</summary>

```
Could not find a plist file at '/Users/unity/Temp/StagingArea/MyGame.app/Contents/PlugIns/bugsnag-osx.bundle/Contents/Info.plist'.
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

```
UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002be] in /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:190 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:95 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```
</details>

I've downgraded to 2020.2.7f1 and it works again

**Comment by yousif-bugsnag** [comment]
Hi @antpaw, thanks for the report! We will look into this when priorities allow.

**Comment by phillipsam** [comment]
Hi @antpaw - the issue you are describing seems related to the one described here: https://forum.unity.com/threads/standalone-build-error-with-bundle-plugin-could-not-find-plist.1082813/

If you click 'Build' and then run up the resulting app, this builds and runs fine and sends error reports to Bugsnag correctly.

I believe that the error you are seeing is not actually an issue with the Bugsnag library. Please do let us know if you have any further comments on this.

**Comment by antpaw** [comment]
Thanks, You might be right about this!
Maybe You could help me with the solution as well?

>  Note - I was able to get around this problem by creating an Info.plist by hand and adding it to the plugin bundle.

I don't really understand how to add a Info.plist file to bugsnag lib?
Should I poke around in this directory? (it is the compiled result)
```
/Users/unity/Temp/StagingArea/MyGame.app/Contents/PlugIns/bugsnag-osx.bundle/Contents/
```
What file content should be in that Info.plist, can it be blank?
Thanks

**Comment by phillipsam** [comment]
Hi @antpaw - we wouldn't recommend adding an Info.plist into the Bugsnag library. As this looks like a Unity issue, it may be worth raising this with them.
In the meantime, you can continue to build your application and run it as per my comment above. It seems that this issue doesn't happen if the application is built and then run separately.

**Comment by mattdyoung** [comment]
Closing as we believe it's a Unity issue, but happy to re-open if there's any evidence Bugsnag is causing this.
