### ISSUE TITLE
Compatibility with Unity 4.7

### ISSUE THREAD

**Issue by CodeHex** [bugsnag/bugsnag-unity#30]
Loading up the example project in Unity 4.7, there seems to be some code that is not compiled in/out correctly. The new notifier code files should be checked that they run using both Unity 5 editor and Unity 4 editor. e.g. !UNITY_LT_5 doesn't work and should be replaced with UNITY_5_OR_NEWER.

**Comment by oddgames-david** [comment]
I got it working on android here with some extra changes I required, you might be interested in player settings stuff for 4.X compatibility.

https://www.dropbox.com/s/pbyhpqcj2qnnp8c/bugsnag.unitypackage?dl=0
