### ISSUE TITLE
Use better folder structure

### ISSUE THREAD

**Issue by oddgames-david** [bugsnag/bugsnag-unity#31]
The folder structure used by bugsnag is quite messy and should be changed so the plugin resides in it's own sub folders, like most other plugins.

This makes it easier to create build systems and keep track of which files belong to Bugsnag.

Plugins
--> Android
-->-->Bugsnag

Bugsnag
--> Editor
-->--> BugsnagPostProcess
--> Busnag.cs

**Comment by kattrali** [comment]
Thank you for the report, @oddgames-david. I’ll take a look.
