### ISSUE TITLE
StackTrace not Splited by Environment.NewLine in Windows

### ISSUE THREAD

**Issue by hecz90** [bugsnag/bugsnag-unity#344]
https://github.com/bugsnag/bugsnag-unity/blob/7f1a552553399fa2f11d28fcd2c2fc633028c9b0/src/BugsnagUnity/Payload/StackTraceLine.cs#L34
Unity joins lines in stracktrace with '\n', but on Windows (non-Unix platform) [Environment.NewLine](https://docs.microsoft.com/en-us/dotnet/api/system.environment.newline) is "\r\n". 
That's why it doesn't split right and puts only one line to the event.

Could you solve this problem?

**Comment by mattdyoung** [comment]
Hi @hecz90 

Thanks for the report. Yes, that looks like a bug - we'll look at fixing this in an upcoming release.

**Comment by johnkiely1** [comment]
Hi @hecz90.

This has now been fixed in the [v5.2.0](https://github.com/bugsnag/bugsnag-unity/releases/tag/v5.2.0) release.

**Comment by hecz90** [comment]
Thanks! It works fine now
