### ISSUE TITLE
iOS 7.1.2 - EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by michaelheiml** [bugsnag/bugsnag-unity#4]
When building on iPad (iOS 7.1.2) XCode (6.1) reports me this after starting the Unity app (Setup within Unity is as the Documentation says):

BugsnagEvent.m +writeEventToDisk:
[[NSFileManager defaultManager] createDirectoryAtPath:[self errorPath] withIntermediateDirectories:YES attributes:nil error:nil];
Thread 1: EXC_BAD_ACCESS (code=1, address=0x25)

![bugsnag](https://cloud.githubusercontent.com/assets/9572772/4919712/85dbf8a4-64fc-11e4-992e-07c064698647.png)

**Comment by ConradIrwin** [comment]
This is now fixed by the latest version of the plugin. See https://bugsnag.com/docs/notifiers/unity for installation guide.
