### ISSUE TITLE
Abort is reported as Out Of Memory (iOS)

### ISSUE THREAD

**Issue by troy-lamerton** [bugsnag/bugsnag-unity#405]
### Describe the bug

Calls to the abort() function are reported as Out Of Memory.

### Steps to reproduce

1. Call `abort()`
2. Restart app so that crash is reported
3. On bugsnag it appears as [Out of Memory](https://app.bugsnag.com/the-naughty-cult-ltd/clash-of-streamers-1/errors/5f9aef5809d334001779cc75?filters[event.since]=7d&filters[app.release_stage]=test&event_id=61670bd0008445138d660000)

### Environment
* Bugsnag version: 5.4.0
* Unity version: 2019.4.16f1
* iOS/Android/macOS/Windows/browser version: iOS 14.7.1
* simulator/emulator or physical device: device
* Initializing bugsnag via a Unity GameObject or in code?: Code
* Player Settings:
    * Scripting backend (Mono or IL2CPP): IL2CPP
    * API compatibility level for .NET: 4.x
    * Stack Trace level for all error types (None/ScriptOnly/Full): ScriptOnly

### Example code snippet 

```cs
public void Reproduce() {
	UnityEngine.Diagnostics.Utils.ForceCrash(ForcedCrashCategory.Abort);
}
```

**Comment by luke-belton** [comment]
Hi @troy-lamerton - Bugsnag relies on our own heuristic to identify during app re-launch whether the previous termination of the app was an unexpected termination by the OS watchdog. We can identify several other known reasons the OS may kill the app such as device reboot, app upgrade, app hang on main thread or thermal kill.

We send an `Out Of Memory` error report that the app was likely terminated by the operating system while in the foreground if all other detectable causes have been ruled out. When we diagnose an OOM, we can't capture a stacktrace so generally we advise looking at breadcrumbs etc. to understand what was happening in the app in the lead up to the event.

There's some more detailed discussion on [this thread](https://github.com/bugsnag/bugsnag-cocoa/issues/1145#issuecomment-875511570) which I'd recommend reading to understand this in more detail.

**Comment by troy-lamerton** [comment]
> Can you tell us a little more about the circumstances in which you're seeing these? Are you able to reproduce the issue at will?

- can reproduce every time with our large Unity app
- cannot reproduce in a small Unity project

> It looks like these OOM events you've linked to are coming from a test release - are these automated tests? Do you see the same issue with a production build or is this only during test runs?

- I open the large app, tap button, it calls `Utils.ForceCrash(ForcedCrashCategory.Abort);`
- Not using automated tests
- Build is made on a cloud machine

> If you're able to provide us with a cut down reproduction example that demonstrates the issue you're seeing that would really help us to investigate.

My cut down project does not reproduce yet. I cannot share the project which reproduces. Below I list the setup for both projects.

Which differences here might cause the misreporting? Please tell me what to try and I will make a reproduction example.

### Large project - reproduces

`SIGABRT` is reported as Out of Memory.

- bugsnag-unity v5.4.0
- Xcode 12
- Xcode build setting `GCC_OPTIMIZATION_LEVEL O1` (Fast)
- ad-hoc build installed from download link
- large workspace containing cocoapods and iOS plugins

### Small project - cannot reproduce

`SIGABRT` is reported as `SIGABRT`.

- bugsnag-unity v5.4.0
- Xcode 13
- Xcode build setting `GCC_OPTIMIZATION_LEVEL Os` (Fastest, Smallest)
- development build installed via Xcode
- just a basic xcode project (no cocoapods)

---

Note that the "Large project" was working correctly with bugsnag-unity v4.8.6 (same build setup and settings). Both projects use Unity 2019.4.16f1.

**Comment by mattdyoung** [comment]
Closing this for now as it sounds like the original reported issue isn't occurring in 5.4.0, but if you can still reproduce the issue then let us know the details and we can re-open and investigate further.
