### ISSUE TITLE
v3.3.2 Bugsnag.unitypackage has compile error with Unity 5.5

### ISSUE THREAD

**Issue by shinjiyoshida** [bugsnag/bugsnag-unity#50]
At Bugsnag.cs line 431, `Application.identifier` is used instead of `Application.bundleIdentifier`.
Maybe Automatic API Updater ran accidentally when exporting Bugsnag.unitypackage.

**Comment by kattrali** [comment]
Thanks for the report, @shinjiyoshida. You're probably right about what happened here 🤔  I'll take a look.
