### ISSUE TITLE
DirectoryNotFoundException: Could not find a part of the path '/storage/emulated/0/Android/data/com.%company_name%/files/Bugsnag/Sessions'.

### ISSUE THREAD

**Issue by RFS-6ro** [bugsnag/bugsnag-unity#554]
### Environment
* Bugsnag version: 6.3.0
* Unity version: 2020.3.30f1
* Android 5.1.1/6.0.1/8.0.0/9/11/5.0
* physical device
* Initializing bugsnag via a Unity GameObject or in code?: through code
* Player Settings:
    * Scripting backend IL2CPP:
    * API compatibility level for .NET: .NET 4.x
    * Stack Trace level for all error types (None/ScriptOnly/Full): Log: None, ScriptOnly for remain

<details><summary>Stack Trace:</summary>
System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) (at <00000000000000000000000000000000>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () (at <00000000000000000000000000000000>:0)
System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <00000000000000000000000000000000>:0)
System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <00000000000000000000000000000000>:0)
System.IO.Directory.GetFiles (System.String path, System.String searchPattern) (at <00000000000000000000000000000000>:0)
BugsnagUnity.FileManager.GetCachedPayloadPaths () (at <00000000000000000000000000000000>:0)
BugsnagUnity.Delivery+<DeliverCachedPayloads>d__11.MoveNext () (at <00000000000000000000000000000000>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)
System.Action.Invoke () (at <00000000000000000000000000000000>:0)
BugsnagUnity.MainThreadDispatchBehaviour.Update () (at <00000000000000000000000000000000>:0)
System.Action:Invoke()
BugsnagUnity.MainThreadDispatchBehaviour:Update()
```

```
</details>

**Comment by luke-belton** [comment]
Hi @RFS-6ro - I haven't been able to reproduce this using the environment settings you gave details of above. Would you be able to share some more details or a cut-down reproduction example please? Do you know what was happening inside your app when the crash happened? Did this first happen e.g. after upgrading the version of `bugsnag-unity` used in your app? Feel free to write into support@bugsnag.com if you want to share a repro case!
