### ISSUE TITLE
7.1.1 New introduced NUllreferenceException when Manually starting Bugsnag

### ISSUE THREAD

**Issue by JinFox** [bugsnag/bugsnag-unity#616]
### Describe the bug
Hello,
SInce the app moved from 7.1.0 to 7.1.1 it seems there is some kind of lifecycle issue when starting bugsnag manually as described here : 
https://docs.bugsnag.com/platforms/unity/#starting-bugsnag-manually
When you play the first time, all is fine, and when stopping/restarting the Editor Run time, there is an increasing amount of NullReferenceException being raised : 
```
NullReferenceException: Object reference not set to an instance of an object
BugsnagUnity.Bugsnag.SetApplicationState (System.Boolean inFocus) (at <3e7eadaa757a4a59b36981258f8053e4>:0)
BugsnagUnity.TimingTrackerBehaviour.OnApplicationPause (System.Boolean paused) (at <3e7eadaa757a4a59b36981258f8053e4>:0)

NullReferenceException: Object reference not set to an instance of an object
BugsnagUnity.Bugsnag.SetApplicationState (System.Boolean inFocus) (at <3e7eadaa757a4a59b36981258f8053e4>:0)
BugsnagUnity.TimingTrackerBehaviour.OnApplicationFocus (System.Boolean hasFocus) (at <3e7eadaa757a4a59b36981258f8053e4>:0)

```

### Steps to reproduce
1. Download the sample project I provided (Or follow the guide in https://docs.bugsnag.com/platforms/unity/#starting-bugsnag-manually)
2. Start Bugsnag manually in script
3. Run the editor Play mode and then stop it
4. Start the Editor Play mode again and see the error
5. Repeating step 3 and 4 will lead to an increasing amount of error being thrown each time.

### Environment
* Bugsnag version:7.1.1
* Unity version:2022.1.14f1
* iOS/Android/macOS/Windows/browser version:Windows 11, in editor
* simulator/emulator or physical device:In Editor
* Initializing bugsnag via a Unity GameObject or in code?:In Code
* Player Settings:
    * Scripting backend (Mono or IL2CPP):N/A
    * API compatibility level for .NET:2.1
    * Stack Trace level for all error types (None/ScriptOnly/Full):Full

I have included a minimal example taken from your repo example with an additional script that launch Bugsnag in script. I have removed my API Key from the config but the issue is present with and without a valid API key
[example.zip](https://github.com/bugsnag/bugsnag-unity/files/9535084/example.zip)

**Comment by rich-bugsnag** [comment]
Thanks for the report!
I'll be looking into this early next week 👍

**Comment by rich-bugsnag** [comment]
Hi @JinFox 
I just pushed a release fixing this.
If you update to version 7.2.0 then this issue will go away.
Please note that after updating you will need to restart unity to make the null refs go away.
Please let me know if you need any more info 👍
