### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by firatgram** [bugsnag/bugsnag-unity#631]
Hello. I'm getting the error in breadcrumbs but not getting an actual report. 

### Environment
* Bugsnag version: 7.1.1
* Unity version: 2021.3.9f1
* Android 9
* Lenovo Tab M10 (FHD) (Lenovo TB-X605L)
* In code game initialization
* Player Settings:
    * Scripting backend (Mono/IL2CPP): IL2CPP
    * API compatibility level for .NET: .NET 2.0
    * Stack Trace level for all error types (None/ScriptOnly/Full): ScriptOnly

<img width="968" alt="Screen Shot 2022-09-26 at 11 43 29" src="https://user-images.githubusercontent.com/112943221/192234657-86c95cee-84b2-4861-bc4f-312764a8bce7.png">

**Comment by luke-belton** [comment]
Hi @firatgram - please could you write into support@bugsnag.com with some links to these errors in your Bugsnag dashboard so that we can investigate this?

**Comment by firatgram** [comment]
Hello. Thank you for the quick reply. I have mailed the details to support.

**Comment by luke-belton** [comment]
For future travellers: closing this out as the query was related to filtering in the Bugsnag dashboard rather than an issue with the `bugsnag-unity` library.
