### ISSUE TITLE
Unity integrate application link 404 during sign-up flow

### ISSUE THREAD

**Issue by swylietoal** [bugsnag/bugsnag-unity#68]
### Expected behavior
unity package is downloaded when clicking link to DL

### Observed behavior
404

### Steps to reproduce
Sign up for account
On step 3, click link bugsnag-unity notifier [https://github.com/bugsnag/bugsnag-unity/blob/master/Bugsnag.unitypackage?raw=true]
404

### Version
na

### Additional information
Submitting as Github issue as the URL is to this repo, could easily be a site issue instead

**Comment by fractalwrench** [comment]
Thanks for the catch @swylietoal - we'll fix that broken link shortly. In the meantime, you can download the Unity Package from [here](https://github.com/bugsnag/bugsnag-unity/releases).
