### ISSUE TITLE
Duplicate symbol when linking with Unity + ARKit

### ISSUE THREAD

**Issue by swylietoal** [bugsnag/bugsnag-unity#69]
### Expected behavior
Bugsnag is able to be added without needing code modification

### Observed behavior
Bugsnag library conflicts with Unity ARKit plugin (StartSession)

### Steps to reproduce
New Unity Project
Import ARKit plugin
Open Example Scene
Add Bugsnag
Run for iOS
   - Xcode build fails with duplicate symbol linker error

#### Can't comment on Issues?
While not technically a blocking issue, this is definitely a friction point for on boarding new apps. Worked around by prefixing StartSession with BS_ in BugsnagUnity.mm and Bugsnag.cs - although a more elegant naming scheme may be better...

**Comment by kattrali** [comment]
Thanks for the report, @swylietoal - can you paste a snippet of the exact wording of the error? This should be a fairly quick fix though I want to be sure there's no other underlying issues.

**Comment by miv** [comment]
@kattrali I've encountered similar error.

```
duplicate symbol _StartSession in:
    /Users/megatron/Library/Developer/Xcode/DerivedData/Unity-iPhone-eizneylhlnjxjwdoxzyzwszpdrde/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/ARSessionNative.o
    /Users/megatron/Library/Developer/Xcode/DerivedData/Unity-iPhone-eizneylhlnjxjwdoxzyzwszpdrde/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/BugsnagUnity.o
ld: 1 duplicate sym
```

And if i understand correctly [this function need renaming](https://github.com/bugsnag/bugsnag-unity/blob/master/src/BugsnagUnity.mm#L156)

Propably wise to append `Bugsnag_` to all extern definitions.

**Comment by kattrali** [comment]
@natalieSED Things have changed fairly significantly since this happened, can you open a new issue with the exact error message that you're seeing?
