### ISSUE TITLE
Race condition around startup can cause null reference exception if application focus changes

### ISSUE THREAD

**Issue by uncapped-shattuck** [bugsnag/bugsnag-unity#781]
### Describe the bug
There is a race condition between the `BugsnagUnity.Bugsnag.InternalClient` being initialized to a non-null value and attempting to use the `InternalClient` indirectly via `TimingTrackingBehaviour.OnApplicationFocus` - the ctor of `BugsnagUnity.Client` initializes the timing tracker, which means that focus changes that happen after the timing tracker starts but before the ctor finishes and the assignment completes will cause a null reference exception.

### Steps to reproduce
This is a race condition with a very narrow window, so the change of reproducing it is low
1. Call `Bugsnag.Start()` in Unity to initialize the client
2. Alt-tab in and out of the Unity window
3. If the timing lines up, see a NullReferenceException in `BugsnagUnity.Bugsnag.SetApplicationState`

### Environment
* Bugsnag version: 7.5.2
* Unity version: 2022.3.6f1
* iOS/Android/macOS/Windows/browser version: Windows 10
* simulator/emulator or physical device: Windows client
* Initializing bugsnag via a Unity GameObject or in code?: Code with backing config scriptable object
* Player Settings:
    * Scripting backend (Mono or IL2CPP): IL2CPP
    * API compatibility level for .NET: .NET Standard 2.1
    * Stack Trace level for all error types (None/ScriptOnly/Full): Full

<details><summary>Error messages:</summary>

```
NullReferenceException: Object reference not set to an instance of an object
  at BugsnagUnity.Bugsnag.SetApplicationState (System.Boolean inFocus) [0x00005] in <de0ea49b4c10449e892e594537b56279>:0 
  at BugsnagUnity.TimingTrackerBehaviour.OnApplicationFocus (System.Boolean hasFocus) [0x00000] in <de0ea49b4c10449e892e594537b56279>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
BugsnagUnity.BugsnagLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
UnityEngine.SystemInfo:GetDeviceModel()
UnityEngine.SystemInfo:get_deviceModel()
BugsnagUnity.Payload.Device:.ctor(Configuration, String)
BugsnagUnity.SessionTracker:StartManagedSession()
BugsnagUnity.SessionTracker:StartSession()
BugsnagUnity.Client:StartInitialSession()
BugsnagUnity.Client:.ctor(INativeClient)
BugsnagUnity.Bugsnag:Start(Configuration)
... <redacted app frames>
```

The stack shows that the client was still being constructed (but was past the point of enabling `BugsnagUnity.TimingTrackerBehaviour`) at the time that Unity broadcast an `OnApplicationFocus` method, and ` BugsnagUnity.TimingTrackerBehaviour.OnApplicationFocus` ultimately depends on the client being fully constructed.

</details>

**Comment by mclack** [comment]
Hi @uncapped-shattuck 

We have now implemented a fix for this in the v8.0.0 release of `bugsnag-unity`: https://github.com/bugsnag/bugsnag-unity/releases/tag/v8.0.0

Please let us know if you notice any other issues after upgrading to this version.
